### ISSUE TITLE
Selection to UML ?

### ISSUE THREAD

**Issue by bakman2** [gorenje/node-red-contrib-flow2uml#1]
This flow works like a charm, but is there a way to only get a selection of a flow to mermaid/uml instead of the whole tab ?

**Comment by gorenje** [comment]
good idea --> implemented in [version 0.1.12](https://flows.nodered.org/node/@gregoriusrippenstein/node-red-contrib-flow2uml)

details: [change at flowhub](https://flowhub.org/f/8e598f0f47194617/diff?v2=7efcc377ab0cc3861f0faed535c8055061c7c016&v1=daafda28150b7c9f80d33085c06a21226e88573c) & [github commit](https://github.com/gorenje/node-red-contrib-flow2uml/commit/7c3a7b3177c257f1adc5b198bff606465920a74b)
