### ISSUE TITLE
http-in node - use the [method] url as description.

### ISSUE THREAD

**Issue by bakman2** [gorenje/node-red-contrib-flow2uml#2]
As subject - for http-in nodes - could the url be used as description ? 
Currently they end up as 'http-in' when there is no name given. But using `url` (including the method) would be much more descriptive and always exist. 

eg. `[GET] /hello`

**Comment by gorenje** [comment]
good idea --> implemented in [version 0.1.12](https://flows.nodered.org/node/@gregoriusrippenstein/node-red-contrib-flow2uml)

details: [change at flowhub](https://flowhub.org/f/8e598f0f47194617/diff?v2=daafda28150b7c9f80d33085c06a21226e88573c&v1=6fb19f5154ed9029fdca50fae42b8898bedefa48) & [github commit](https://github.com/gorenje/node-red-contrib-flow2uml/commit/6600293f1e2f460ba4094a2b052edb2c31867a3b)
